services:
  autofilm:
    image: yquark/autofilm:latest
    container_name: autofilm
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
      - ./media:/media
      - ./logs:/logs
    environment:
      TZ: Asia/Shanghai
      AUTOFILM_WEB_ENABLED: "true"
      AUTOFILM_WEB_HOST: 0.0.0.0
      AUTOFILM_WEB_PORT: "8000"
